/*
 * cross-chain-hackathon api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

import (
	"errors"
)

// DividendApiService is a service that implents the logic for the DividendApiServicer
// This service should implement the business logic for every endpoint for the DividendApi API. 
// Include any external packages or services that will be required by this service.
type DividendApiService struct {
}

// NewDividendApiService creates a default api service
func NewDividendApiService() DividendApiServicer {
	return &DividendApiService{}
}

// TxDividendGet - get a CrossTx to be signed
func (s *DividendApiService) TxDividendGet(estateId string, perShare int64) (interface{}, error) {
	// TODO - update TxDividendGet with the required logic for this service method.
	// Add api_dividend_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.
	return nil, errors.New("service method 'TxDividendGet' not implemented")
}
