/*
 * cross-chain-hackathon api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

import (
	"database/sql"
	"log"

	"github.com/jmoiron/sqlx"

	"github.com/datachainlab/cross-chain-hackathon/backend/apiserver/rdb"
)

// EstateApiService is a service that implents the logic for the EstateApiServicer
// This service should implement the business logic for every endpoint for the EstateApi API.
// Include any external packages or services that will be required by this service.
type EstateApiService struct {
}

// NewEstateApiService creates a default api service
func NewEstateApiService() EstateApiServicer {
	return &EstateApiService{}
}

// GetEstateById - get an estate and its trade data
func (s *EstateApiService) GetEstateById(estateId string) (interface{}, error) {
	db, err := rdb.InitDB()
	if err != nil {
		log.Println(err)
		return nil, ErrorFailedDBConnect
	}

	/* HACK the following process should be improved. */
	estate := &Estate{}
	if err := db.Get(estate, "SELECT * FROM estate WHERE tokenId = ?", estateId); err != nil {
		log.Println(err)
		return nil, ErrorFailedDBGet
	}
	if estate.Trades, err = s.getTrades(db, estate.TokenId); err != nil {
		return nil, err
	}
	return estate, nil
}

// GetEstates - get all estates
func (s *EstateApiService) GetEstates() (interface{}, error) {
	db, err := rdb.InitDB()
	if err != nil {
		log.Println(err)
		return nil, ErrorFailedDBConnect
	}
	estates := &[]Estate{}
	if err := db.Select(estates, "SELECT * FROM estate ORDER BY tokenId"); err != nil {
		log.Println(err)
		return nil, ErrorFailedDBGet
	}

	for i := 0; i < len(*estates); i++ {
		trades, err := s.getTrades(db, (*estates)[i].TokenId)
		if err != nil {
			return nil, err
		}
		log.Printf("id: %s\ttrades: %+v\n", (*estates)[i].TokenId, trades)
		(*estates)[i].Trades = trades
	}
	log.Printf("estates: %+v\n", estates)

	return estates, nil
}

func (s *EstateApiService) getTrades(db *sqlx.DB, estateId string) ([]Trade, error) {
	trades := []Trade{}
	rows, err := db.Query("SELECT id, estateId, unitPrice, amount, buyer, seller, type, status, updatedAt FROM trade WHERE estateId = ?", estateId)
	if err != nil {
		log.Println(err)
		return nil, err
	}
	for rows.Next() {
		t := Trade{}
		var buyer sql.NullString
		if err := rows.Scan(&t.Id, &t.EstateId, &t.UnitPrice, &t.Amount, &buyer, &t.Seller, &t.Type, &t.Status, &t.UpdatedAt); err != nil {
			log.Println(err)
			return nil, ErrorFailedDBGet
		}
		if buyer.Valid {
			t.Buyer = buyer.String
		}
		trades = append(trades, t)
	}

	for i := 0; i < len(trades); i++ {
		reqs, err := SelectTradeRequestByTradeId(db, trades[i].Id)
		if err != nil {
			return nil, err
		}
		trades[i].Requests = reqs
	}
	return trades, nil
}
