/*
 * cross-chain-hackathon api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

import (
	"net/http"
	"strings"
)

// A DividendApiController binds http requests to an api service and writes the service results to the http response
type DividendApiController struct {
	service DividendApiServicer
}

// NewDividendApiController creates a default api controller
func NewDividendApiController(s DividendApiServicer) Router {
	return &DividendApiController{service: s}
}

// Routes returns all of the api route for the DividendApiController
func (c *DividendApiController) Routes() Routes {
	return Routes{
		{
			"TxDividendGet",
			strings.ToUpper("Get"),
			"/api/tx/dividend",
			c.TxDividendGet,
		},
	}
}

// TxDividendGet - get a CrossTx to be signed
func (c *DividendApiController) TxDividendGet(w http.ResponseWriter, r *http.Request) {
	query := r.URL.Query()
	estateId := query.Get("estateId")
	perShare, err := parseIntParameter(query.Get("perShare"))
	if err != nil {
		w.WriteHeader(500)
		return
	}

	result, err := c.service.TxDividendGet(estateId, perShare)
	if err != nil {
		w.WriteHeader(500)
		return
	}

	EncodeJSONResponse(result, nil, w)
}
