/*
 * cross-chain-hackathon api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

import (
	"errors"
)

// TxApiService is a service that implents the logic for the TxApiServicer
// This service should implement the business logic for every endpoint for the TxApi API. 
// Include any external packages or services that will be required by this service.
type TxApiService struct {
}

// NewTxApiService creates a default api service
func NewTxApiService() TxApiServicer {
	return &TxApiService{}
}

// TxDividendGet - get a CrossTx to be signed
func (s *TxApiService) TxDividendGet(estateId string, perShare int64) (interface{}, error) {
	// TODO - update TxDividendGet with the required logic for this service method.
	// Add api_tx_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.
	return nil, errors.New("service method 'TxDividendGet' not implemented")
}

// TxTradeRequestGet - get a CrossTx to be signed
func (s *TxApiService) TxTradeRequestGet(tradeId int64, from string) (interface{}, error) {
	// TODO - update TxTradeRequestGet with the required logic for this service method.
	// Add api_tx_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.
	return nil, errors.New("service method 'TxTradeRequestGet' not implemented")
}
