/*
 * cross-chain-hackathon api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

// ChannelInfo - defined by cross
type ChannelInfo struct {

	Port string `json:"port"`

	Channel string `json:"channel"`
}
