/*
 * cross-chain-hackathon api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

import (
	"time"
)

type Trade struct {

	// generated by the API server
	Id int64 `json:"id"`

	EstateId string `json:"estateId"`

	UnitPrice int64 `json:"unitPrice"`

	Amount int64 `json:"amount"`

	Buyer string `json:"buyer,omitempty"`

	Seller string `json:"seller"`

	Type TradeType `json:"type"`

	Requests []TradeRequest `json:"requests"`

	Status TradeStatus `json:"status"`

	UpdatedAt time.Time `json:"updatedAt"`
}
