/*
 * cross-chain-hackathon api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

type TradeRequestStatus int32

// List of TradeRequestStatus
const (
	REQUEST_OPENED TradeRequestStatus = 0
	REQUEST_CANCELED TradeRequestStatus = 1
	REQUEST_ONGOING TradeRequestStatus = 2
	REQUEST_COMPLETED TradeRequestStatus = 3
	REQUEST_FAILED TradeRequestStatus = 4
)
