/*
 * cross-chain-hackathon api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

type User struct {

	Id string `json:"id"`

	Name string `json:"name"`

	Mnemonic string `json:"mnemonic"`
}
