/*
 * cross-chain-hackathon api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

type TradeStatus int32

// List of TradeStatus
const (
	TRADE_OPENED TradeStatus = 0
	TRADE_CANCELED TradeStatus = 1
	TRADE_COMPLETED TradeStatus = 2
)
