/*
 * cross-chain-hackathon api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

type PostTradeRequestInput struct {

	// generated by the API server
	TradeId int64 `json:"tradeId"`

	From string `json:"from"`

	CrossTx CrossTx `json:"crossTx"`
}
