/*
 * cross-chain-hackathon api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

// OpValue - Write(K, V) or Read(K)
type OpValue struct {

	K string `json:"K"`

	V string `json:"V,omitempty"`
}
